CREATE TABLE SERIAJACK.T_TEXTE_REGLEMENTAIRE (
    ID NUMBER NOT NULL,
    TYPE VARCHAR2(20) NOT NULL,
    NUMERO  VARCHAR2(50) NOT NULL,
    INTITULE VARCHAR2(255) NOT NULL,
    DATE_CREATION DATE NOT NULL,
    FICHIER Blob  NOT NULL,
    PRECISION VARCHAR2(255),
    DATE_CERTIFICATION DATE,
    DATE_PARUTION DATE,
    NUMERO_JONC VARCHAR2(15),
    DATE_ABROGATION DATE,
    REFERENCE VARCHAR2(50),
    LIEN_JURIDOC VARCHAR2(50)
);

CREATE SEQUENCE SERIAJACK.SEQ_TTEXTEREG INCREMENT BY 1 START WITH 1 MINVALUE 1 CACHE 20;